% for i = 2:param.nMeasure
i = 2;
j = 1;
jp =1;
            mMomentsNew(i,j) = 0;

            mMomentsNew(i,j) = mMomentsNew(i,j) + (1 - mHat(1,jp)) * param.inv_S(jp) * param.transS(jp,j)*...
                    mParameters(1,jp)*param.QuadratureWeights'*(((mAssetsPrimeQuadrature(:,jp)-...
                    mMomentsNew(1,j)).^i).* exp(squeeze(gridAMoments(:,:,jp))*...
                    mParameters(2:param.nMeasure+1,jp)));
            % +mHat(1,jp)*param.transS(jp,j)*param.inv_S(jp)*...
            %         ((mAssetsPrimeBC(1,jp)- mMomentsNew(1,j)).^i);
